import { AdWithStore } from "@/types/database";

export const MOCK_ADS: AdWithStore[] = [
    {
        id: "1",
        store_id: "s1",
        image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
        ad_copy: "🔥 Notre nouvelle collection arrives ! Découvrez des pièces exclusives qui vont transformer votre style. Livraison gratuite partout en Afrique. Commandez maintenant avant rupture de stock !",
        cta_link: "https://fashionking.shop/products/collection-ete",
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        store: { id: "s1", page_name: "Fashion King", domain: "fashionking.shop", favicon_url: "https://www.google.com/s2/favicons?domain=shopify.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "2",
        store_id: "s2",
        image_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/movie.mp4",
        ad_copy: "✨ Perdez du poids sans effort avec nos suppléments naturels ! Des milliers de clients satisfaits. Résultats garantis en 30 jours ou remboursement intégral. Profitez de -50% aujourd'hui seulement.",
        cta_link: "https://healthboost.store/products/slim-formula",
        created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        store: { id: "s2", page_name: "Health Boost", domain: "healthboost.store", favicon_url: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "3",
        store_id: "s3",
        image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
        ad_copy: "💎 Le bijou dont vous avez toujours rêvé. Fabriqué à la main, or 18 carats, livraison express 24h. Offrez-vous le luxe à prix accessible. Stock limité !",
        cta_link: "https://luxejewels.co/collections/gold",
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        store: { id: "s3", page_name: "Luxe Jewels", domain: "luxejewels.co", favicon_url: "https://www.google.com/s2/favicons?domain=etsy.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "4",
        store_id: "s4",
        image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/movie.mp4",
        ad_copy: "🚀 La formation qui va changer votre vie ! Apprenez à générer 5000€/mois depuis votre téléphone. Plus de 10 000 étudiants déjà formés. Places limitées — Inscrivez-vous maintenant.",
        cta_link: "https://ecomacademy.fr/formation-ecom",
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        store: { id: "s4", page_name: "Ecom Academy", domain: "ecomacademy.fr", favicon_url: "https://www.google.com/s2/favicons?domain=gumroad.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "5",
        store_id: "s5",
        image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
        ad_copy: "👟 Les sneakers les plus hypes de la saison sont là ! Édition limitée, coloris exclusif. Déjà portées par vos artistes préférés. Ne manquez pas cette opportunité unique.",
        cta_link: "https://sneakervault.shop/products/hype-edition",
        created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        store: { id: "s5", page_name: "Sneaker Vault", domain: "sneakervault.shop", favicon_url: "https://www.google.com/s2/favicons?domain=shopify.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "6",
        store_id: "s6",
        image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/movie.mp4",
        ad_copy: "🌿 Soins naturels 100% bio pour une peau éclatante. Sans parabènes, sans sulfates. Formulés par des dermatologues africains pour les peaux noires. Essayez pendant 14 jours, satisfait ou remboursé.",
        cta_link: "https://skinglowco.com/collections/bio",
        created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        store: { id: "s6", page_name: "Skin Glow Co", domain: "skinglowco.com", favicon_url: "https://www.google.com/s2/favicons?domain=woocommerce.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "7",
        store_id: "s7",
        image_url: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
        ad_copy: "📱 Coque iPhone ultra résistante avec impression personnalisée ! Votre photo, votre design, votre style. Résiste aux chutes de 3 mètres. Commande en 2 minutes, livraison en 48h.",
        cta_link: "https://customcase.fr/products/iphone-custom",
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        store: { id: "s7", page_name: "Custom Case", domain: "customcase.fr", favicon_url: "https://www.google.com/s2/favicons?domain=shopify.com&sz=64", created_at: new Date().toISOString() },
    },
    {
        id: "8",
        store_id: "s8",
        image_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=700&fit=crop",
        video_url: "https://www.w3schools.com/html/movie.mp4",
        ad_copy: "🏋️ Matériel de sport professionnel à domicile. Plus besoin de salle de sport ! Transformez votre corps en 60 jours avec notre programme complet. Livraison et montage offerts.",
        cta_link: "https://fitzone.shop/products/home-kit",
        created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        store: { id: "s8", page_name: "Fit Zone", domain: "fitzone.shop", favicon_url: "https://www.google.com/s2/favicons?domain=shopify.com&sz=64", created_at: new Date().toISOString() },
    },
];

export const MOCK_STATS = {
    scannedToday: 1_247,
    totalStores: 384,
    newWinners: 23,
};
